[tool.poetry]
name = "pxknowledge-graph"
version = "0.0.11"
description = ""
authors = ["franciscsimon <francisc.simon@pantopix.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pxinfra = "0.0.32"
prefect = "^3.1.0"
requests = "^2.32.3"
jinja2 = "^3.1.4"
httpx = "0.27.2"


[[tool.poetry.source]]
name = "pantopix"
url = "https://cache.hz.pantopix.net/repository/pypi-private/simple/"
priority = "supplemental"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
